### PR TITLE
fix setup script

### PR DESCRIPTION
**Pull request by kevinhughes27**
fixes the setup script from crashing when looking for README.rst which has been renamed to README.md

### CODE REVIEW

**Comment by kevinhughes27** [comment]
is this being maintained?

**Comment by mikeshultz** [comment]
This would be quite helpful in deployment.  Fix is good.

**Comment by kevinhughes27** [comment]
No activity here, I'm going to close 😞

**Comment by jacobcrp** [comment]
Hi all,

A new Python wrapper has been written by @robrem:

github: https://github.com/robrem/opensecrets-crpapi
PyPI: https://pypi.python.org/pypi/opensecrets-crpapi/0.1.2

J

**Comment by robrem** [comment]
Great, thanks so much for the mention! My twitter handle is @jrobrem (includes a "j"), which is different than my github name. 

Best,
Rob

**Pull request closed without merging**
